path: .
train: C:\Users\fadhil\Documents\Vscode\Github\gelatik-datamining-2025\data\flame_satellite\train
val: C:\Users\fadhil\Documents\Vscode\Github\gelatik-datamining-2025\data\flame_satellite\valid
names:
  0: fire